n = input('Digite um valor: ')
print(n.isalnum)
print(n.isalpha)
print(n.isupper)
print(n.istitle)
print(n.isspace)
print(n.isprintable)
print(n.islower)
print(n.isdigit)
print(n.isidentifier)
print(n.isnumeric)
print(n.isdigit)
print(n.isascii)